apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - name: gateway
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/gateway:$VERSION
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: STORAGE_ACCOUNT_NAME
          value: $STORAGE_ACCOUNT_NAME
        - name: STORAGE_ACCESS_KEY
          value: $STORAGE_ACCESS_KEY
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
            
    readinessProbe:
      httpGet:
        path: /healthz
        port: 5000
        initialDelaySeconds: 5
        periodSeconds: 15

      livenessProbe:
        httpGet:
          path: /healthz
          port: 5000
          initialDelaySeconds: 5
          periodSeconds: 2
    
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000