apiVersion: apps/v1
kind: Deployment
metadata:
  name: edittime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edittime
  template:
    metadata:
      labels:
        app: edittime
    spec:
      containers: 
      - name: edittime
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/edittime:$VERSION
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: STORAGE_ACCOUNT_NAME
          value: $STORAGE_ACCOUNT_NAME
        - name: STORAGE_ACCESS_KEY
          value: $STORAGE_ACCESS_KEY
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: edittime
spec:
  selector:
    app: edittime
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000